USE [master]
GO

/****** Object:  Database [meta]    Script Date: 2/14/2021 7:11:22 PM ******/
CREATE DATABASE [meta]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'meta', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\meta.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'meta_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\meta_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [meta].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [meta] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [meta] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [meta] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [meta] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [meta] SET ARITHABORT OFF 
GO

ALTER DATABASE [meta] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [meta] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [meta] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [meta] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [meta] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [meta] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [meta] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [meta] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [meta] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [meta] SET  DISABLE_BROKER 
GO

ALTER DATABASE [meta] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [meta] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [meta] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [meta] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [meta] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [meta] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [meta] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [meta] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [meta] SET  MULTI_USER 
GO

ALTER DATABASE [meta] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [meta] SET DB_CHAINING OFF 
GO

ALTER DATABASE [meta] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [meta] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [meta] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [meta] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [meta] SET QUERY_STORE = OFF
GO

ALTER DATABASE [meta] SET  READ_WRITE 
GO


