USE META;
-- ================================================
-- TESTE - META
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		DILENO S SANTOS
-- CREATE DATE: 15/02/2021
-- DESCRIPTION:	RETORNA ITENS DO ORÇAMENTO
-- =============================================
CREATE FUNCTION [DBO].[FN_RETORNA_ITENS_ORCAMENTO]
(	
	  @pIDORCAMENTO INT
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
			  I.ID AS CODITEM
			 ,I.ID_ORCAMENTO AS CODORCAMENTO
			 ,I.ID_PRODUTO AS CODPRODUTO
			 ,P.NOME AS NOMEPRODUTO
			 ,P.PRECO AS VLRUNITARIO
			 ,I.QTD AS QTDPRODUTOS
			 ,I.VALOR AS VLRTOTAL
	FROM DBO.TBORCAMENTOS_ITENS I WITH(NOLOCK)
	INNER JOIN DBO.TBPRODUTOS P WITH(NOLOCK) ON P.ID = I.ID_PRODUTO
	WHERE I.ID_ORCAMENTO = @pIDORCAMENTO	
	AND I.STATUS != 'I'
)
GO
