USE META;
-- ================================================
-- TESTE - META
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		DILENO S SANTOS
-- CREATE DATE: 15/02/2021
-- DESCRIPTION:	RETORNA ORÇAMENTO
-- =============================================
CREATE FUNCTION [DBO].[FN_RETORNA_ORCAMENTO]
(	
	  @pIDORCAMENTO INT
	 ,@pIDCLIENTE INT
)
RETURNS TABLE 
AS
RETURN 
(
	SELECT
			 O.ID AS CODORCAMENTO
			,O.ID_CLIENTE AS CODCLIENTE
			,C.NOME AS NOMECLIENTE
			,O.QTDTOTALPRODUTOS AS QTDPRODUTOS
			,O.VLROTOTALRCAMENTO AS VLRPRODUTOS
			,O.DATAORCAMENTO AS DTAORCAMENTO
	FROM DBO.TBORCAMENTOS O WITH(NOLOCK)
	INNER JOIN DBO.TBCLIENTES C WITH(NOLOCK) ON C.ID = O.ID_CLIENTE
	WHERE O.ID = @pIDORCAMENTO
	AND O.ID_CLIENTE = ISNULL(@pIDCLIENTE,O.ID_CLIENTE)
	AND O.STATUS != 'I'
)
GO
