USE [meta]
GO

/****** Object:  Table [dbo].[TBORCAMENTO]    Script Date: 2/14/2021 7:10:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBORCAMENTOS](
	[ID] [int] NOT NULL,
	[ID_CLIENTE] [int] NOT NULL,
	[QTDTOTALPRODUTOS] [int] NULL,
	[VLROTOTALRCAMENTO] [numeric](18, 0) NULL,
	[DATAORCAMENTO] [datetime] NULL,
	[STATUS] [char](1) NOT NULL,
 CONSTRAINT [PK_TBORCAMENTOS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'A - ATIVO; I - INATIVO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBORCAMENTOS', @level2type=N'COLUMN',@level2name=N'STATUS'
GO

ALTER TABLE [dbo].[TBORCAMENTOS] ADD  CONSTRAINT [DF_TBORCAMENTOS_STATUS]  DEFAULT ('A') FOR [STATUS]
GO

ALTER TABLE [dbo].[TBORCAMENTOS]  WITH CHECK ADD  CONSTRAINT [FK_TBORCAMENTOS_CLIENTES] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[TBCLIENTES] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TBORCAMENTOS] CHECK CONSTRAINT [FK_TBORCAMENTOS_CLIENTES]
GO
