USE [meta]
GO

/****** Object:  Table [dbo].[TBORCAMENTOS_ITENS]    Script Date: 2/15/2021 1:32:18 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBORCAMENTOS_ITENS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ID_ORCAMENTO] [int] NOT NULL,
	[ID_PRODUTO] [int] NOT NULL,
	[QTD] [int] NULL,
	[VALOR] [numeric](18, 0) NULL,
	[STATUS] [char](1) NOT NULL,
 CONSTRAINT [PK_TBORCAMENTOS_ITENS_ITENS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[ID_ORCAMENTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBORCAMENTOS_ITENS] ADD  CONSTRAINT [DF_TBORCAMENTOS_ITENS_VALOR]  DEFAULT ((0)) FOR [VALOR]
GO

ALTER TABLE [dbo].[TBORCAMENTOS_ITENS] ADD  CONSTRAINT [DF_TBORCAMENTOS_ITENS_STATUS]  DEFAULT ('T') FOR [STATUS]
GO

ALTER TABLE [dbo].[TBORCAMENTOS_ITENS]  WITH CHECK ADD  CONSTRAINT [FK_TBORCAMENTOS_ITENS_ORCAMENTOS] FOREIGN KEY([ID_ORCAMENTO])
REFERENCES [dbo].[TBORCAMENTOS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TBORCAMENTOS_ITENS] CHECK CONSTRAINT [FK_TBORCAMENTOS_ITENS_ORCAMENTOS]
GO

ALTER TABLE [dbo].[TBORCAMENTOS_ITENS]  WITH CHECK ADD  CONSTRAINT [FK_TBORCAMENTOS_ITENS_PRODUTOS] FOREIGN KEY([ID_PRODUTO])
REFERENCES [dbo].[TBPRODUTOS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[TBORCAMENTOS_ITENS] CHECK CONSTRAINT [FK_TBORCAMENTOS_ITENS_PRODUTOS]
GO

EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'T - TEMPORARIO; A - ATIVADO; I - INATIVADO' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'TABLE',@level1name=N'TBORCAMENTOS_ITENS', @level2type=N'COLUMN',@level2name=N'STATUS'
GO


