USE [C:\PROJECTS\META\TESTEMETA\TESTEMETA\APP_DATA\BD_META.MDF]
GO

/****** Object:  StoredProcedure [dbo].[USP_INSERECLIENTES]    Script Date: 2/14/2021 7:38:49 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- AUTHOR:		DILENO S SANTOS
-- CREATE DATE: 14/02/2021
-- DESCRIPTION:	INSERIR CLIENTES
-- =============================================
CREATE PROCEDURE [dbo].[USP_INSERECLIENTES](@pNOMECLIENTE VARCHAR(100), @pTELEFONE VARCHAR(20))
	AS
BEGIN

	SET NOCOUNT ON;

	IF @pNOMECLIENTE IS NULL
		RETURN;

	BEGIN TRY
		INSERT INTO TBCLIENTES (NOME,TELEFONE) VALUES (@pNOMECLIENTE,@pTELEFONE);
	END TRY
	BEGIN CATCH
			SELECT
				 ERROR_NUMBER() AS NUMERRO
				,ERROR_MESSAGE() AS MENSAGEMERRO
	END CATCH;
END
GO


