USE [C:\PROJECTS\META\TESTEMETA\TESTEMETA\APP_DATA\BD_META.MDF];
GO

/****** Object:  StoredProcedure [dbo].[USP_INSEREPRODUTOS]    Script Date: 2/14/2021 7:43:41 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- AUTHOR:		DILENO S SANTOS
-- CREATE DATE: 14/02/2021
-- DESCRIPTION:	INSERIR PRODUTOS
-- =============================================
CREATE PROCEDURE [dbo].[USP_INSEREPRODUTOS](@PNOMEPRODUTO VARCHAR(100), @PPRECO NUMERIC(18,0))
	AS
BEGIN

	SET NOCOUNT ON;

	IF @PNOMEPRODUTO IS NULL
		RETURN;

	IF @PPRECO IS NULL
		RETURN;

	BEGIN TRY
		INSERT INTO TBPRODUTOS(NOME,PRECO) VALUES (@PNOMEPRODUTO,@PPRECO);
	END TRY
	BEGIN CATCH
			SELECT
				 ERROR_NUMBER() AS NUMERRO
				,ERROR_MESSAGE() AS MENSAGEMERRO
	END CATCH;
END
GO


