USE [meta]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- AUTHOR:		DILENO S SANTOS
-- CREATE DATE: 14/02/2021
-- DESCRIPTION:	ATUALIZA ORÇAMENTO
-- =============================================
CREATE PROCEDURE [dbo].[USP_ATUALIZA_ORCAMENTO](@pIDORCAMENTO INT)
	AS
BEGIN	

	SET NOCOUNT ON;

	BEGIN TRY

		DECLARE @vVLRTT NUMERIC(18,0);
			SET @vVLRTT = 0.00;

		IF @pIDORCAMENTO IS NULL
			RETURN;

		IF ((SELECT DBO.FN_EXISTEORCAMENTO(@pIDORCAMENTO)) = 1)
		BEGIN	
			IF ((SELECT DBO.FN_EXISTEM_ITENS_ORCAMENTO(@pIDORCAMENTO)) > 0)
			BEGIN
				--ATUALIZA O STATUS DOS ITENS
				UPDATE DBO.TBORCAMENTOS_ITENS 
					SET STATUS = 'A'
				WHERE ID_ORCAMENTO = @pIDORCAMENTO;
				--RECALCULA O TOTAL DO ORÇAMENTO
				UPDATE TBORCAMENTOS
					SET QTDTOTALPRODUTOS = I.QTT,
						VLROTOTALRCAMENTO = I.VTT
				FROM DBO.TBORCAMENTOS O
				INNER JOIN (SELECT 
									I.ID_ORCAMENTO,
									SUM(I.QTD) AS QTT,
									SUM(I.QTD * I.VALOR) AS VTT
							FROM TBORCAMENTOS_ITENS I
							GROUP BY I.ID_ORCAMENTO) I ON O.ID = I.ID_ORCAMENTO
				WHERE O.ID = @pIDORCAMENTO;
			END;
		END

	END TRY
	BEGIN CATCH
			SELECT
				 ERROR_NUMBER() AS NUMERRO
				,ERROR_MESSAGE() AS MENSAGEMERRO
	END CATCH;
END
GO

/*
DROP TABLE #TEMPDILENO;

CREATE TABLE #TEMPDILENO 
(
	ID INT,
	VLR NUMERIC(18,0)
)

INSERT INTO #TEMPDILENO (ID,VLR) VALUES (1,10.00);
INSERT INTO #TEMPDILENO (ID,VLR) VALUES (5,15.00);


SELECT 
		SUM(ID*VLR)
FROM #TEMPDILENO
*/