USE [meta]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- =============================================
-- AUTHOR:		DILENO S SANTOS
-- CREATE DATE: 14/02/2021
-- DESCRIPTION:	INSERIR ITENS DO ORÇAMENTO
-- =============================================
CREATE PROCEDURE [dbo].[USP_INSEREORCAMENTOS_ITENS](@pIDORCAMENTO INT, @pIDPRODUTO INT, @pQTD INT)
	AS
BEGIN	

	SET NOCOUNT ON;

	BEGIN TRY
		DECLARE @vVLRPRD NUMERIC(18,0);
			SET @vVLRPRD = 0.00;
		DECLARE @vVLRTT NUMERIC(18,0);
			SET @vVLRTT = 0.00;

		IF @pIDORCAMENTO IS NULL
			RETURN;
		IF @pIDPRODUTO IS NULL
			RETURN;
		IF @pQTD IS NULL
			SET @pQTD = 0;

		SET @vVLRPRD = (SELECT TOP 1 PRECO FROM TBPRODUTOS P WITH(NOLOCK));
		IF @vVLRPRD IS NOT NULL
			SET @vVLRTT = (@pQTD * @vVLRPRD);

		IF ((SELECT DBO.FN_EXISTEORCAMENTO(@pIDORCAMENTO)) = 1)
		BEGIN		
			INSERT INTO DBO.TBORCAMENTOS_ITENS (ID_ORCAMENTO,ID_PRODUTO,QTD,VALOR) VALUES (@pIDORCAMENTO,@pIDPRODUTO,@pQTD,@vVLRTT);
		END;

	END TRY
	BEGIN CATCH
			SELECT
				 ERROR_NUMBER() AS NUMERRO
				,ERROR_MESSAGE() AS MENSAGEMERRO
	END CATCH;
END
GO


