USE META;
-- ================================================
-- TESTE - META
-- ================================================
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		DILENO S SANTOS
-- CREATE DATE: 14/02/2021
-- DESCRIPTION:	ORÇAMENTO
-- =============================================
CREATE PROCEDURE DBO.USP_ORCAMENTOS(@pIDCLIENTE INT,@pTIPO BIT,@pIDORCAMENTO INT = 0)	
	AS
BEGIN
	DECLARE @vVLRTOTAL NUMERIC(18,0) = 0.00;
	DECLARE @vVALORC BIT = 0; --ORÇAMENTO: 0 - NÃO EXISTE | 1 - EXISTE
	/*
		@TIPO :
			0 : INSERIR; 
			1 : ALTERAR; PERMITIDO ALTERAR SOMENTE O CLIENTE
			2 : EXCLUIR; O PEDIDO É INATIVADO
	*/

	SET NOCOUNT ON;

	IF @pIDCLIENTE IS NULL
		RETURN;

	BEGIN TRY
		--SE O CLIENTE NÃO EXISTIR, NÃO FAZ NADA
		IF (SELECT dbo.FN_EXISTECLIENTE(@pIDCLIENTE)) = 0
			RETURN;

		--SE É ALTERAR OU DELETAR...
		IF @pTIPO IN (1,2)
		BEGIN			
			IF @pIDORCAMENTO > 0
			BEGIN
				--SE O ORÇAMENTO NÃO EXISTIR, NÃO FAZ NADA
				IF (SELECT dbo.FN_EXISTEORCAMENTO(@pIDORCAMENTO)) = 0
					RETURN
				ELSE
					SET @vVALORC = 1;
			END;
		END;

		--INSERT
		IF @pTIPO = 0
		BEGIN
				INSERT INTO DBO.TBORCAMENTOS (ID_CLIENTE,QTDTOTALPRODUTOS,VLROTOTALRCAMENTO,DATAORCAMENTO) VALUES
											 (@pIDCLIENTE,0,0.00,GETDATE());
		END;

		--SE ORÇAMENTO EXISTIR
		IF @vVALORC = 1
		BEGIN
			--UPDATE
			IF @pTIPO = 1
			BEGIN
				--INATIVA ORÇAMENTO
				UPDATE DBO.TBORCAMENTOS SET ID_CLIENTE = @pIDCLIENTE
				WHERE ID = @pIDORCAMENTO;
			END;

			--DELETE
			IF @pTIPO = 2
			BEGIN
				--INATIVA ITENS DO ORÇAMENTO
				UPDATE DBO.TBORCAMENTOS SET STATUS = 'I'
				WHERE ID = @pIDORCAMENTO;
			END;
		END;		
	END TRY
	BEGIN CATCH
			SELECT
				 ERROR_NUMBER() AS NUMERRO
				,ERROR_MESSAGE() AS MENSAGEMERRO
	END CATCH;
END
GO
