SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- AUTHOR:		DILENO S SANTOS
-- CREATE DATE: 14/02/2021
-- DESCRIPTION:	ALTERA CLIENTES
-- =============================================
CREATE PROCEDURE [dbo].[USP_EXCLUIRCLIENTES](@PID INT)
AS
BEGIN
	SET NOCOUNT ON;
	IF @PID IS NULL
		RETURN;
	DELETE FROM TBCLIENTES WHERE ID = @PID;
END
GO